language: objective-c
osx_image: xcode9.3
script:
    - xcodebuild clean test -workspace Bindy.xcworkspace -scheme Bindy -destination "platform=iOS Simulator,name=iPhone 7,OS=11.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
