language: objective-c
osx_image: xcode11
script:
    - xcodebuild clean test -workspace Bindy.xcworkspace -scheme Bindy -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=13.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
